version: '3.1'

services:

  # The main database server
  # For convenience it is exposes to the host and used during tests
  hsqldb:
    image: java:alpine
    volumes:
      - ./db/target/hsqldb.jar:/var/hsqldb.jar:z
      - ./db/data:/var/data:Z
    command: java -cp /var/hsqldb.jar org.hsqldb.Server -database.0 file:/var/data/monolith -dbname.0 monolith
    ports:
      - 9001:9001

  # A unique database server to the account microservice
  hsqldb-account:
    image: java:alpine
    volumes:
      - ./db/target/hsqldb.jar:/var/hsqldb.jar:z
      - ./db/data:/var/data:Z
    command: java -cp /var/hsqldb.jar org.hsqldb.Server -database.0 file:/var/data/account -dbname.0 account

  # A unique database server to the transaction microservice
  hsqldb-transaction:
    image: java:alpine
    volumes:
      - ./db/target/hsqldb.jar:/var/hsqldb.jar:z
      - ./db/data:/var/data:Z
    command: java -cp /var/hsqldb.jar org.hsqldb.Server -database.0 file:/var/data/transaction -dbname.0 transaction

  # the runnable account microservice
  account:
    image: java:alpine
    volumes:
#      # mount the hand maintained config file in the container
#      - ./account/src/conf/config.json:/var/config.json:z
      - ./account/target/account-1.0.0-fat.jar:/var/app.jar:z
#    # run the application with the provider configuration json
#    command: java -jar /var/app.jar -conf /var/config.json -cluster
    command: java -jar /var/app.jar -cluster
    environment:
      DBHOST: hsqldb-account:9001
      DBNAME: account
      DBUSERNAME: postgres
      DBPASSWORD: password

  # the runnable transaction microservice
  transaction:
    image: java:alpine
    volumes:
#      # mount the hand maintained config file in the container
#      - ./transaction/src/conf/config.json:/var/config.json:z
      - ./transaction/target/transaction-1.0.0-fat.jar:/var/app.jar:z
#    # run the application with the provider configuration json
#    command: java -jar /var/app.jar -conf /var/config.json -cluster
    command: java -jar /var/app.jar -cluster
    environment:
      DBHOST: hsqldb-account:9001
      DBNAME: account
      DBUSERNAME: postgres
      DBPASSWORD: password

  # the web frontend application and API entrypoint
  web:
    image: java:alpine
    volumes:
      - ./web/target/web-1.0.0-fat.jar:/var/app.jar:z
    command: java -jar /var/app.jar -cluster
    ports:
      - 80:8080
    environment:
      CLIENTID: 598d9e50aae1d575926b
      CLIENTSECRET: dc6ef4fc7e76c8becbd4d3369b284499ef54632a

#  # The initial monolith
#  monolith:
#    image: java:alpine
#    volumes:
#      - ./monolith/target/monolith-1.0.0.jar:/var/app.jar:z
#    command: java -jar /var/app.jar
#    ports:
#      - 80:8080
