version: '3.1'

services:

  # The main database server
  hsqldb:
    image: java:alpine
    volumes:
      - ./db/target/hsqldb.jar:/var/hsqldb.jar:z
      - ./db/data/monolith.properties:/var/lib/monolith.properties:Z
      - ./db/data/monolith.script:/var/lib/monolith.script:Z
    command: java -cp /var/hsqldb.jar org.hsqldb.Server -database.0 file:/var/lib/monolith -dbname.0 monolith
    ports:
      - 9001:9001

  # The initial monolith
  monolith:
    image: java:alpine
    volumes:
      - ./monolith/target/monolith-1.0.0.jar:/var/app.jar:z
    command: java -jar /var/app.jar
    ports:
      - 80:8080
